"""Initial migration

Revision ID: 7738511edb09
Revises: 
Create Date: 2024-11-18 12:08:40.212939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7738511edb09'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('privacy_policy_consent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_table('info_glavnoe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_info_glavnoe_id'), 'info_glavnoe', ['id'], unique=False)
    op.create_table('meetings_at_office',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('date_of_meeting', sa.String(length=10), nullable=False),
    sa.Column('meeting_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('privacy_policy_consent', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_at_office_id'), 'meetings_at_office', ['id'], unique=False)
    op.create_table('services_offered',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('link_to_photo', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_offered_id'), 'services_offered', ['id'], unique=False)
    op.create_table('foundations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('link_to_photo', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('service_offered_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_offered_id'], ['services_offered.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foundations_id'), 'foundations', ['id'], unique=False)
    op.create_index(op.f('ix_foundations_service_offered_id'), 'foundations', ['service_offered_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_foundations_service_offered_id'), table_name='foundations')
    op.drop_index(op.f('ix_foundations_id'), table_name='foundations')
    op.drop_table('foundations')
    op.drop_index(op.f('ix_services_offered_id'), table_name='services_offered')
    op.drop_table('services_offered')
    op.drop_index(op.f('ix_meetings_at_office_id'), table_name='meetings_at_office')
    op.drop_table('meetings_at_office')
    op.drop_index(op.f('ix_info_glavnoe_id'), table_name='info_glavnoe')
    op.drop_table('info_glavnoe')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
